# Generated by Django 5.1.3 on 2024-12-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('short answer', 'short answer'), ('long answer', 'long answer'), ('multiple choices', 'multiple choices'), ('checkbox', 'checkbox')], max_length=100),
        ),
    ]
