# Generated by Django 5.1.3 on 2024-12-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_responseanswer_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Responses',
        ),
    ]
